INSERT INTO company (companyName,parentCompanyName) VALUES
	 ('Loblaws','Loblaw Companies Limited '),
	 ('No Frills','Loblaw Companies Limited '),
	 ('Zehrs Markets','Loblaw Companies Limited '),
	 ('Real Canadian Superstore','Loblaw Companies Limited '),
	 ('T & T Supermarket','Loblaw Companies Limited '),
	 ('Bloor Street Market','Loblaw Companies Limited '),
	 ('Dominion','Loblaw Companies Limited '),
	 ('Atlantic Cash & Carry','Loblaw Companies Limited '),
	 ('Atlantic Superstore','Loblaw Companies Limited '),
	 ('Axep','Loblaw Companies Limited ');
INSERT INTO company (companyName,parentCompanyName) VALUES
	 ('Les Entrepots Presto','Loblaw Companies Limited '),
	 ('Extra Foods','Loblaw Companies Limited '),
	 ('Fortinos','Loblaw Companies Limited '),
	 ('Freshmart','Loblaw Companies Limited '),
	 ('L''Intermarche','Loblaw Companies Limited '),
	 ('Shoppers Drug Mart / Pharmaprix','Loblaw Companies Limited '),
	 ('Lucky Dollar Foods','Loblaw Companies Limited '),
	 ('Maxi / Maxi & Cie','Loblaw Companies Limited '),
	 ('NG Cash & Carry','Loblaw Companies Limited '),
	 ('Your Independent Grocer / Independent CityMarket','Loblaw Companies Limited ');
INSERT INTO company (companyName,parentCompanyName) VALUES
	 ('Provigo','Loblaw Companies Limited '),
	 ('Shop Easy Foods','Loblaw Companies Limited '),
	 ('Shoppers Drug Mart / Pharmaprix','Loblaw Companies Limited '),
	 ('SuperValu','Loblaw Companies Limited '),
	 ('Valu-mart','Loblaw Companies Limited '),
	 ('Wholesale Club / Club Entrepot','Loblaw Companies Limited '),
	 ('Sobeys','Empire Company Limited'),
	 ('FreshCo','Empire Company Limited'),
	 ('Farm Boy','Empire Company Limited'),
	 ('Foodland','Empire Company Limited');
INSERT INTO company (companyName,parentCompanyName) VALUES
	 ('Longo''s ','Empire Company Limited'),
	 ('Lawtons','Empire Company Limited'),
	 ('Needs Convenience','Empire Company Limited'),
	 ('IGA / IGA Extra','Empire Company Limited'),
	 ('Marche Bonichoix','Empire Company Limited'),
	 ('Marche Tradition','Empire Company Limited'),
	 ('Rachelle-Bery','Empire Company Limited'),
	 ('Safeway','Empire Company Limited'),
	 ('Thrifty Foods','Empire Company Limited'),
	 ('Pete''s Frootique','Empire Company Limited');
INSERT INTO company (companyName,parentCompanyName) VALUES
	 ('Metro','Metro Inc.'),
	 ('Food Basics','Metro Inc.'),
	 ('Marche Adonis','Metro Inc.'),
	 ('Marche AMI','Metro Inc.'),
	 ('Marche Extra','Metro Inc.'),
	 ('Marche Richelieu','Metro Inc.'),
	 ('Les 5 Saisons','Metro Inc.'),
	 ('Super C','Metro Inc.'),
	 ('AG Foods','Pattison Food Group'),
	 ('Bulkley Valley Wholesale','Pattison Food Group');
INSERT INTO company (companyName,parentCompanyName) VALUES
	 ('Buy-Low Foods','Pattison Food Group'),
	 ('Choices Markets','Pattison Food Group'),
	 ('Meinhardt Fine Foods','Pattison Food Group'),
	 ('Natures Fare Markets','Pattison Food Group'),
	 ('Nesters Market','Pattison Food Group'),
	 ('PriceSmart Foods','Pattison Food Group'),
	 ('Quality Foods','Pattison Food Group'),
	 ('Save-On-Foods','Pattison Food Group'),
	 ('Urban Fare','Pattison Food Group'),
	 ('49th Parallel Grocery','');
INSERT INTO company (companyName,parentCompanyName) VALUES
	 ('Ambrosia Natural Foods',''),
	 ('Asian Food Centre',''),
	 ('Askew''s Foods',''),
	 ('Avril (Health Supermarket)',''),
	 ('Brunos Fine Foods',''),
	 ('Centra Food Market',''),
	 ('Coleman''s',''),
	 ('Co-op Atlantic',''),
	 ('Valu Foods',''),
	 ('Village Food Stores','');
INSERT INTO company (companyName,parentCompanyName) VALUES
	 ('Coppa''s Fresh Market',''),
	 ('Country Grocer',''),
	 ('Dutchie''s',''),
	 ('Fairway Markets',''),
	 ('Family Foods',''),
	 ('Calgary Co-op','Federated Co-operatives'),
	 ('Heritage Co-op (Western Manitoba)','Federated Co-operatives'),
	 ('North Central Co-op','Federated Co-operatives'),
	 ('Red River Co-op','Federated Co-operatives'),
	 ('Saskatoon Co-op','');
INSERT INTO company (companyName,parentCompanyName) VALUES
	 ('Foodex',''),
	 ('FoodFare',''),
	 ('Fresh City Market',''),
	 ('Freson Bros.',''),
	 ('Galleria Supermarkets',''),
	 ('Georgia Main Food Group',''),
	 ('Fresh St. Market',''),
	 ('IGA / MarketPlace IGA in British Columbia only',''),
	 ('Goodness Me!',''),
	 ('Grande Cheese','');
INSERT INTO company (companyName,parentCompanyName) VALUES
	 ('H Mart',''),
	 ('Highland Farms',''),
	 ('Italian Centre Shop',''),
	 ('Kim Phat',''),
	 ('Le Jardin Mobile',''),
	 ('L&M Markets (Hometown Grocers Co-op)',''),
	 ('Lalumiere Bonanza',''),
	 ('Le Marche Esposito',''),
	 ('Le Marche Vegetarien/Les Arpents Verts',''),
	 ('Lococo''s','');
INSERT INTO company (companyName,parentCompanyName) VALUES
	 ('Lucky Supermarket',''),
	 ('Marche Adonis',''),
	 ('Mike Dean Local Grocer',''),
	 ('Nations Fresh Food',''),
	 ('Nature''s Emporium',''),
	 ('Northern','The North West Company'),
	 ('NorthMart','The North West Company'),
	 ('Organic Garage',''),
	 ('Panchvati Supermarket',''),
	 ('P.A.T. Mart','');
INSERT INTO company (companyName,parentCompanyName) VALUES
	 ('Planet Organic',''),
	 ('Pomme Natural Market',''),
	 ('Rabba Fine Foods',''),
	 ('Quality Foods',''),
	 ('Starsky Fine Foods',''),
	 ('Sungiven Foods',''),
	 ('Sunterra Market',''),
	 ('Supermarche PA',''),
	 ('SuperValu',''),
	 ('TaiKo Supermarket','');
INSERT INTO company (companyName,parentCompanyName) VALUES
	 ('Vince''s Market',''),
	 ('Vincenzo''s',''),
	 ('Yummy Market',''),
	 ('Costco',''),
	 ('Dollarama',''),
	 ('Jean Coutu Group',''),
	 ('London Drugs',''),
	 ('Walmart Canada',''),
	 ('Whole Foods Market',''),
	 ('Pusateri''s','');
INSERT INTO company (companyName,parentCompanyName) VALUES
	 ('Giant Tiger',''),
	 ('M&M Food Market',''),
	 ('Bulk Barn',NULL),
	 ('Beaver Fishery',NULL),
	 ('Starfish Caribbean Market',NULL),
	 ('Aisle 24',NULL),
	 ('Alex Farm Products',NULL),
	 ('Bespoke Butchers',NULL),
	 ('Carload Food Market Ltd',NULL),
	 ('Cobs Bread',NULL);
INSERT INTO company (companyName,parentCompanyName) VALUES
	 ('Mike''s Fish Market',NULL),
	 ('Nosso Talho Partnership',NULL),
	 ('Pancho''s Bakery Inc',NULL),
	 ('Mabel''s Bakery',NULL),
	 ('Summerhill Market',NULL),
	 ('The Big Carrot',NULL),
	 ('Saint Germain Bakery',NULL),
	 ('Nasim Caravan',NULL),
	 ('The Kitchen Table',NULL),
	 ('Marcheleo''s Marketplace',NULL);
INSERT INTO company (companyName,parentCompanyName) VALUES
	 ('Whitehouse Meats',NULL),
	 ('Hooked',NULL),
	 ('Bakery On The Go',NULL),
	 ('Forno Cultura',NULL),
	 ('Sunny Foodmart',NULL),
	 ('Sanagan''s Meat Locker',NULL),
	 ('Commisso Bros & Racco Italian Bakery',NULL),
	 ('Navs Grocery',NULL),
	 ('Bun King Bakery',NULL),
	 ('Rowe Farm',NULL);
INSERT INTO company (companyName,parentCompanyName) VALUES
	 ('H-Mart',NULL),
	 ('Fresh 1 Market',NULL),
	 ('Bestco Food Mart',NULL),
	 ('Cumbraes',NULL),
	 ('Fine Food Market',NULL),
	 ('De La Mer Fresh Fish Market',NULL),
	 ('Galleria Supermarket',NULL),
	 ('Sak''s Fine Foods',NULL),
	 ('Kera Fresh Meat',NULL),
	 ('Savours Fresh Market',NULL);
INSERT INTO company (companyName,parentCompanyName) VALUES
	 ('Tienda Movil Latin Supermarket',NULL),
	 ('Bruno''s Fine Foods',NULL),
	 ('Tavora Sea Products',NULL),
	 ('Capri Bagels & Buns',NULL),
	 ('Tung Hing Bakery',NULL),
	 ('Karlovo',NULL),
	 ('Grande Cheese Company',NULL),
	 ('Global Cheese Shoppe',NULL),
	 ('Baharak Market',NULL),
	 ('Columbus Bakery',NULL);
INSERT INTO company (companyName,parentCompanyName) VALUES
	 ('Kristapsons',NULL),
	 ('Win Win Fresh Meat',NULL),
	 ('G Prasad Caribbean & Oriental Specialty Foods',NULL),
	 ('Gloucester Bakery',NULL),
	 ('The Friendly Butcher',NULL),
	 ('Chinese Bakery',NULL);